### PR TITLE
Remove security email address, for issue 404.

### PR DESCRIPTION
**Pull request by warmana**
Change requested in issue #404 by @DLEEMOJ , who has checked this draft.

Now submitting for inclusion.

### CODE REVIEW

**Comment by warmanaMOJ** [comment]
Hello @cybersquirrel and @L-Crosby 

Please may I request approval to publish this update? It implements the change requested in issue #404, and the content has been checked by @DLEEMOJ .

The change is to remove the security@ email address as a contact point for first line help in secure disposal of physical or on-premise assets.

The updated page can be previewed [here](https://github.com/warmana/security-guidance/blob/issue404/docs/secure-disposal-of-it-physical-and-on-premise.md).

A full set of the changes in this publication may be seen in the 'files changed' tab at the top of this PR.

NB: The PR was created using an updated copy of the build tooling. This has introduced some minor markdown formatting changes on some of the other pages; there are no content changes, however.

Many thanks.

**Review by cybersquirrel — COMMENTED** [review]
Are these two suppliers still 'approved' and if so, by whom? Would it be better to remove the company names and just point people to the helpdesk.

**Comment by warmana** [comment]
Thank you @cybersquirrel .

As per your feedback, and following discussions with @DLEEMOJ , the specific providers have been removed, in favour of a simple advisory to contact helpdesk.

A preview of the updated page may be seen [here](https://github.com/warmana/security-guidance/blob/issue404/docs/secure-disposal-of-it-physical-and-on-premise.md#approved-organisations).

Many thanks.

**Comment by cybersquirrel** [comment]
LGTM - thank you for making these changes!

Jon.

**Comment by warmanaMOJ** [comment]
Thank you @cybersquirrel  - please could either you or @L-Crosby approve this review, ready for publication?

Thanks again.

**Review by cybersquirrel — APPROVED** [review]
Apologies - rusty with GitHub and took me a while to find my way back to the bit of the UI to actually approve the change! All good from my perspective.

**Pull request merged**
