### PR TITLE
Document how to request a manual SSL cert

### PR DESCRIPTION
**Pull request by SteveMarshall**
There have been a few cases where it would have been useful to have this in the same place as the automated certificate guidance, so I'm adding it.

### CODE REVIEW

**Comment by warmanaMOJ** [comment]
@cybersquirrel Please may I request your review/approval to publish this helpful addition from @SteveMarshall ? Thank you.

**Comment by cybersquirrel** [comment]
Curious as to the "should" rather than "must" - any particular rationale for that @SteveMarshall? Otherwise all looks good to me.

**Comment by warmanaMOJ** [comment]
Lovely job, thanks all.

**Comment by SteveMarshall** [comment]
@cybersquirrel @warmana Thanks for reviewing so quickly! 💯 would PR again ✊🏼

**Comment by joelgsamuel** [comment]
https://github.com/ministryofjustice/security-guidance/graphs/contributors

phew, not bumped yet ;-)

**Pull request merged**
