### PR TITLE
Update what LastPass use case

### PR DESCRIPTION
**Pull request by AntonyBishop**
Amendments to LastPass use case to reflect current practices and avoid confusion around who can have an account.

### CODE REVIEW

**Review by NickWalt01 — APPROVED** [review]

**Comment by warmanaMOJ** [comment]
Hi @AntonyBishop and @NickWalt01 

I've incorporated your proposed changes into our documentation source, and created a preview build. You can see the resulting draft [here](https://github.com/ministryofjustice/security-guidance/blob/lastpass0310/docs/using-lastpass.md#using-lastpass-enterprise).

If you're happy that this correctly reflects your PR, please add a +1 or LGTM here. I'll then get the updates formally approved for publication.

Many thanks.

**Comment by AntonyBishop** [comment]
Hi Adrian,

LGTM.

Many thanks

Tony

**Comment by warmanaMOJ** [comment]
@AntonyBishop Thank you. Putting this into the publishing pipeline now.

**Comment by AntonyBishop** [comment]
Many thanks.

**Comment by warmanaMOJ** [comment]
Content updates now [published](https://security-guidance.service.justice.gov.uk/using-lastpass/#who-should-use-it).

*Many* thanks for the feedback!

**Pull request closed without merging**
